name: run-tests

on: workflow_dispatch #we can manually trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install php and composer
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          args: --ignore-platform-reqs
      - name: create .env file
        run: cp .env.example .env
      - name: create app key
        run: php artisan key:generate
      - name: run tests
        run: php artisan test
